trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

stages:
- stage: Build
  displayName: Build and Test
  jobs:
  - job: BuildAndTest
    displayName: Build and Test Application
    steps:
    - task: UseDotNet@2
      displayName: Install .NET SDK
      inputs:
        packageType: 'sdk'
        version: '8.x'

    - script: |
        dotnet restore EmployeeManagementApp.sln
        dotnet build EmployeeManagementApp.sln --configuration $(buildConfiguration)
        dotnet test EmployeeManagementApp.sln --no-build --verbosity normal
      displayName: Build and Test .NET Application

    - task: PublishBuildArtifacts@1
      displayName: Publish Build Artifacts
      inputs:
        PathtoPublish: '$(System.DefaultWorkingDirectory)/bin/$(buildConfiguration)/net8.0/publish'
        ArtifactName: 'drop'
